modLoader = "kotlinforforge"
loaderVersion = "[5.3,)"
issueTrackerURL = "https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues"
license = "Apache-2.0"

[[mods]]
modId = "vs_eureka"
version = "${version}"
displayName = "VS Eureka Mod"
authors = ["Tri0de", "ewoudje", "VS2 Discord Artists"]
description = '''
Basically Archimedes Ships, but with VS2 as the backend!
'''
logoFile = "icon.png"

[[mixins]]
config = "vs_eureka-common.mixins.json"

[[mixins]]
config = "vs_eureka.mixins.json"

[[dependencies.vs_eureka]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.125,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_eureka]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_eureka]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[${vs2_version},)"
ordering = "AFTER"
side = "BOTH"